### ISSUE TITLE
 A workaround using NFS Mounting

### ISSUE THREAD

**Issue by freemandealer** [gojuno/mainframer#158]
I regret I didn't know mainframer sooner. I would have been thrilled several months ago if I see this, since I was looking for something exactly like this at that time. It's amazing!

However I have already figured out a workaround using NFS mounting. I mount my local project directory onto a remote powerful server so that I can edit codes locally while build codes remotely. The configuration is simple, workflow is tidy, most importantly, I can freely choose where to run the executables.

**Comment by artem-zinnatullin** [comment]
We started with similar idea of mounting filesystem over network, but this approach didn't scale well:

* Different desktop OSes provide very different level of quality for network mounting depending on selected protocol.
* We didn't find a good solution for working offline and transparent sync once you get back online
* Build performance will depend on capability of your network between local and remote machine a LOT, because almost each file read will go over network, this will slow down build process tremendously, we tried to play with different settings of caching but that resulted in inconsistent file system states very soon.

Then we tried `tar` + `gzip/pgzip` + `scp` + `ssh`, but `scp` is very simple and not very performant if you only change parts of the project files.

So, we're here using `rsync` and `ssh` :)
