### ISSUE TITLE
Extract local and remote excludes as configurable parameters

### ISSUE THREAD

**Issue by AntonRutkevich** [gojuno/mainframer#19]
lines like 
```--exclude='artifacts' \```
or 
```--exclude='kotlin' \``` 
show that it is still bound to a particular project. 

It might me a good idea to extract it. 

As separate files?
```.localignore```
```.remoteignore```
?

**Comment by artem-zinnatullin** [comment]
So, initially we did not want to do so because it'll obligate us on supporting multiple build systems, but looks like it's required step and we can just provide list of samples for build systems we work with and let the community create their own setups for other build systems.

Since it's breaking change, let's do it in 2.0.0!
